format = """
[](fg:#6272A4)\
$username\
[](fg:#6272A4 bg:#FF79C6)\
$directory\
[](fg:#FF79C6 bg:#FFB86C)\
$git_branch\
$git_status\
[](fg:#FFB86C bg:#8BE9FD)\
$haskell\
$python\
[](fg:#8BE9FD bg:#BD93F9)\
$time\
[ ](fg:#BD93F9)\
"""

# Disable the blank line at the start of the prompt
add_newline = true

[username]
show_always = true
style_user = "bg:#6272A4"
style_root = "bg:#6272A4"
format = '[$user ]($style)'
disabled = false

[directory]
style = "bg:#FF79C6"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
style = "bg:#FFB86C"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#FFB86C"
format = '[$all_status$ahead_behind ]($style)'

[haskell]
style = "bg:#8BE9FD"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:#8BE9FD"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#BD93F9"
format = '[ $time ]($style)'
